# Master

In [1]:
import sys; sys.path.append("..")
import warnings; warnings.filterwarnings("ignore")
import numpy as np
import pandas as pd
from pathlib import Path
import lightgbm as lgb
from src.data import load_master
from src.select import null_importance

INTERIM = Path("../data/interim")

In [2]:
X, y = load_master()
X.shape

(307511, 3028)

# Null importance

Target-permutation importance. Fit a GBM once on the real target for actual gain, then many times on a **shuffled** target for a null gain distribution per feature. Each feature is judged against **itself** under a broken target — same distribution, cardinality and correlations — so the noise floor is fair (a random-noise probe mis-sets it because its distribution doesn't match the real features). Keep a feature only if its real gain beats its **own** 95th-percentile null. Fast fit (subsample + fixed trees) keeps the shuffles cheap.

In [3]:
gbm = lambda: lgb.LGBMClassifier(n_estimators=400, learning_rate=0.05, num_leaves=31,
                                 min_child_samples=50, subsample=0.8, colsample_bytree=0.7,
                                 n_jobs=-1, verbose=-1)
res = null_importance(gbm, X, y, k=20, n=80_000)
res.head(30)

null run  1/20
null run  2/20
null run  3/20
null run  4/20
null run  5/20
null run  6/20
null run  7/20
null run  8/20
null run  9/20
null run 10/20
null run 11/20
null run 12/20
null run 13/20
null run 14/20
null run 15/20
null run 16/20
null run 17/20
null run 18/20
null run 19/20
null run 20/20

,actual,null_mean,null_95,null_max,keep
ext_source_mean,21767.775468,268.621161,375.366689,429.073634,True
ext_source_median,11745.253679,290.909762,452.159394,487.648033,True
credit_to_goods,2879.287025,301.556277,417.415948,421.751139,True
ext_2_3,2306.729718,378.944405,441.194988,466.798450,True
credit_to_annuity,1718.768555,316.022613,399.169208,540.802921,True
AMT_ANNUITY,1706.324236,376.813113,471.637000,522.727288,True
ext_source_max,1647.955853,327.718446,451.346447,480.177149,True
days_employed_percentage,1493.460193,432.283310,547.133795,602.316329,True
ext_source_min,1444.469131,317.263090,394.355887,409.742573,True
prev_DAYS_LAST_DUE_1ST_VERSION_max,1349.901253,237.420178,355.543467,401.418990,True
EXT_SOURCE_1_to_birth,1319.569963,321.186929,433.224078,476.331458,True
DAYS_EMPLOYED,1295.844174,389.150033,512.383754,580.376638,True
EXT_SOURCE_3,1191.987369,441.205782,572.660316,574.136738,True
cc_util_max_6,1174.575657,56.498763,108.621768,215.813290,True
cc_util_max_12,1168.072513,39.509211,70.797635,103.653069,True
annuity_income_percentage,1054.964885,439.845916,582.461955,619.657926,True
ins_late_max_730,984.490119,194.217449,367.871113,416.697411,True
NAME_EDUCATION_TYPE_Secondary_secondary_special,983.216939,16.353353,37.669871,40.994899,True
bureau_debt_credit,953.124500,243.172086,373.552179,400.123991,True
DAYS_BIRTH,806.187599,375.878789,547.028383,630.462531,True
prev_appr_AMT_ANNUITY_sum,782.598539,171.160672,299.356196,302.345330,True
DAYS_REGISTRATION,747.618141,509.101411,652.721694,654.517668,True
ins_days_late_sum,744.733745,282.308123,382.201945,424.341747,True
ins_last_loan_late_max,720.477087,195.841932,322.261922,359.621293,True
prev_credit_goods_ratio_mean,714.115611,191.771932,268.152688,285.865739,True
ext_source_std,704.934112,728.554509,888.797347,895.068639,False
credit_per_non_child,696.303447,301.628024,409.885399,419.969791,True
DEF_30_CNT_SOCIAL_CIRCLE,684.217811,27.925189,73.335037,75.677131,True
ext_source_mean_to_birth,675.556369,400.164155,572.581929,582.568260,True
payment_rate,661.849029,254.348060,348.610365,376.317590,True

# Keep

In [4]:
kept = res.index[res["keep"]].tolist()
print(len(kept), "kept /", len(res), "| real gain beats own 95th-pct null")
res[res["keep"]].head(30)

354 kept / 3028 | real gain beats own 95th-pct null

,actual,null_mean,null_95,null_max,keep
ext_source_mean,21767.775468,268.621161,375.366689,429.073634,True
ext_source_median,11745.253679,290.909762,452.159394,487.648033,True
credit_to_goods,2879.287025,301.556277,417.415948,421.751139,True
ext_2_3,2306.729718,378.944405,441.194988,466.798450,True
credit_to_annuity,1718.768555,316.022613,399.169208,540.802921,True
AMT_ANNUITY,1706.324236,376.813113,471.637000,522.727288,True
ext_source_max,1647.955853,327.718446,451.346447,480.177149,True
days_employed_percentage,1493.460193,432.283310,547.133795,602.316329,True
ext_source_min,1444.469131,317.263090,394.355887,409.742573,True
prev_DAYS_LAST_DUE_1ST_VERSION_max,1349.901253,237.420178,355.543467,401.418990,True
EXT_SOURCE_1_to_birth,1319.569963,321.186929,433.224078,476.331458,True
DAYS_EMPLOYED,1295.844174,389.150033,512.383754,580.376638,True
EXT_SOURCE_3,1191.987369,441.205782,572.660316,574.136738,True
cc_util_max_6,1174.575657,56.498763,108.621768,215.813290,True
cc_util_max_12,1168.072513,39.509211,70.797635,103.653069,True
annuity_income_percentage,1054.964885,439.845916,582.461955,619.657926,True
ins_late_max_730,984.490119,194.217449,367.871113,416.697411,True
NAME_EDUCATION_TYPE_Secondary_secondary_special,983.216939,16.353353,37.669871,40.994899,True
bureau_debt_credit,953.124500,243.172086,373.552179,400.123991,True
DAYS_BIRTH,806.187599,375.878789,547.028383,630.462531,True
prev_appr_AMT_ANNUITY_sum,782.598539,171.160672,299.356196,302.345330,True
DAYS_REGISTRATION,747.618141,509.101411,652.721694,654.517668,True
ins_days_late_sum,744.733745,282.308123,382.201945,424.341747,True
ins_last_loan_late_max,720.477087,195.841932,322.261922,359.621293,True
prev_credit_goods_ratio_mean,714.115611,191.771932,268.152688,285.865739,True
credit_per_non_child,696.303447,301.628024,409.885399,419.969791,True
DEF_30_CNT_SOCIAL_CIRCLE,684.217811,27.925189,73.335037,75.677131,True
ext_source_mean_to_birth,675.556369,400.164155,572.581929,582.568260,True
payment_rate,661.849029,254.348060,348.610365,376.317590,True
prev_appr_CNT_PAYMENT_std,645.299481,228.876641,351.282226,352.155941,True

# Save

In [5]:
pd.Series(kept, name="feature").to_csv(INTERIM / "null_importance_features.csv", index=False)
len(kept)

354